### ISSUE TITLE
Flight duration is resetting

### ISSUE THREAD

**Issue by sternschnaube** [Pepperoni-Jabroni/RandomizedDefaultFireworks#2]
Example: While I craft one stack of Flight duration 3 rockets, after using one rocket, the whole stack is resetting the Flight duration.

Do you think it's possible to fix?

**Comment by Pepperoni-Jabroni** [comment]
Fixed in the latest version, thanks for reporting!

**Comment by venaminecraft** [comment]
Thank you!!
